"""Download Oswald / IBM Plex Sans / IBM Plex Mono (latin + latin-ext subsets) from Google Fonts
into app/web/vendor/fonts and write a local fonts.css, so the app never needs the internet
for its fonts. Re-run only if the font list changes. Run in the foreground."""
import os, re, sys, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "..", "app", "web", "vendor", "fonts"))
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
URL = ("https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700"
       "&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500;600&display=swap")

def get(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=60).read()

css = get(URL).decode("utf-8")
blocks = re.findall(r"/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})", css, re.S)
keep = [(sub, b) for sub, b in blocks if sub in ("latin", "latin-ext")]
os.makedirs(OUT, exist_ok=True)
seen, out_css = {}, []
for sub, b in keep:
    m = re.search(r"url\((https://[^)]+\.woff2)\)", b)
    remote = m.group(1)
    if remote not in seen:
        fam = re.search(r"font-family: '([^']+)'", b).group(1).replace(" ", "")
        wt = re.search(r"font-weight: ([^;]+);", b).group(1).replace(" ", "-")
        name = f"{fam}-{wt}-{sub}.woff2"
        with open(os.path.join(OUT, name), "wb") as f:
            f.write(get(remote))
        seen[remote] = name
    out_css.append(f"/* {sub} */\n" + b.replace(remote, seen[remote]))
with open(os.path.join(OUT, "fonts.css"), "w", encoding="utf-8") as f:
    f.write("/* Local copy of the Google Fonts CSS (SIL Open Font License). Generated by tools/fonts/fetch_fonts.py */\n")
    f.write("\n".join(out_css) + "\n")
print(len(keep), "font-face blocks,", len(seen), "files")
